// Conversation-history PDF export. Builds a clean, branded printable report of the
// session and opens the browser print dialog (Save as PDF) — a local export that
// preserves the full Q/A, generated ZCQL, and cited evidence for the case file.
export function exportConversationPdf({ messages, role, language }) {
  const esc = (s) => String(s ?? '').replace(/[&<>]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]));
  const now = new Date().toLocaleString('en-IN');
  const turns = messages.map((m) => {
    if (m.role === 'user') return `<div class="q"><b>Q:</b> ${esc(m.text)}</div>`;
    const cites = (m.citations || []).map((c) => `${esc(c.type)}:${esc(c.id)}`).join(', ');
    return `<div class="a"><b>Response:</b><div class="atext">${esc(m.text)}</div>` +
      (m.zcql ? `<div class="meta"><b>Query:</b> <code>${esc(m.zcql)}</code></div>` : '') +
      (cites ? `<div class="meta"><b>Cited evidence:</b> ${esc(cites)}</div>` : '') +
      `</div>`;
  }).join('');

  const html = `<!doctype html><html><head><meta charset="utf-8"><title>KSP Crime AI — Conversation Report</title>
  <style>
    body{font-family:Segoe UI,Arial,sans-serif;color:#111;max-width:820px;margin:0 auto;padding:32px;}
    .hd{display:flex;align-items:center;gap:12px;border-bottom:3px solid #1e3a8a;padding-bottom:14px;margin-bottom:6px;}
    .hd .sh{width:42px;height:42px;border-radius:9px;background:linear-gradient(135deg,#3d8bfd,#22d3ee);display:flex;align-items:center;justify-content:center;font-size:22px;}
    .hd h1{font-size:18px;margin:0;color:#1e3a8a;} .hd p{margin:2px 0 0;font-size:11px;color:#666;}
    .info{font-size:11px;color:#666;margin:10px 0 20px;}
    .q{background:#f1f5fb;border-left:3px solid #3d8bfd;padding:10px 12px;margin:16px 0 6px;border-radius:0 6px 6px 0;font-size:13px;}
    .a{padding:4px 4px 4px 12px;font-size:13px;} .atext{white-space:pre-wrap;margin:6px 0;line-height:1.55;}
    .meta{font-size:11px;color:#555;margin-top:5px;} code{background:#f0f0f0;padding:1px 5px;border-radius:4px;font-size:11px;}
    .ft{margin-top:30px;border-top:1px solid #ddd;padding-top:10px;font-size:10px;color:#999;text-align:center;}
  </style></head><body>
    <div class="hd"><div class="sh">🛡️</div><div><h1>KSP Crime Intelligence — Conversation Report</h1>
    <p>Karnataka State Police · Confidential · Synthetic data</p></div></div>
    <div class="info">Generated: ${now} &nbsp;·&nbsp; Role: ${esc(role)} &nbsp;·&nbsp; Language: ${language === 'kn' ? 'Kannada' : 'English'}</div>
    ${turns}
    <div class="ft">Every response is grounded in the crime database and traceable via the audit log. Generated by KSP Crime Intelligence AI on Zoho Catalyst.</div>
  </body></html>`;

  const w = window.open('', '_blank');
  if (!w) { alert('Please allow pop-ups to export the PDF.'); return; }
  w.document.write(html);
  w.document.close();
  w.focus();
  setTimeout(() => w.print(), 400);
}
